version: '3'
services:
  influxdb:
    image: influxdb:1.8.10-alpine
    container_name: influxdb
    networks:
      - default-internal-network
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb/storage:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - default-internal-network
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
  node-red:
    image: nodered/node-red:latest
    container_name: nodered
    environment:
      - TZ=Europe/Paris
    networks:
      - default-internal-network
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data

networks:
  default-internal-network: